import { CommandEncoder } from "../../../layagl/CommandEncoder";
import { BaseTexture } from "../../../resource/BaseTexture";
import { BufferTargetType, BufferUsage } from "../../RenderEnum/BufferTargetType";
import { RenderCapable } from "../../RenderEnum/RenderCapable";
import { RenderClearFlag } from "../../RenderEnum/RenderClearFlag";
import { RenderParams } from "../../RenderEnum/RenderParams";
import { IRender2DContext } from "../../RenderInterface/IRender2DContext";
import { IRenderBuffer } from "../../RenderInterface/IRenderBuffer";
import { IRenderDrawContext } from "../../RenderInterface/IRenderDrawContext";
import { IRenderEngine } from "../../RenderInterface/IRenderEngine";
import { IRenderShaderInstance } from "../../RenderInterface/IRenderShaderInstance";
import { IRenderVertexState } from "../../RenderInterface/IRenderVertexState";
import { ITextureContext } from "../../RenderInterface/ITextureContext";
import { RenderStateCommand } from "../../RenderStateCommand";
import { WebGLMode } from "../WebGLEngine/GLEnum/WebGLMode";
import { WebGlConfig } from "../WebGLEngine/WebGLConfig";
import { IRenderOBJCreate } from "../../RenderInterface/IRenderOBJCreate";
import { ShaderDataType } from "../../RenderShader/ShaderData";
import { RenderStatisticsInfo } from "../../RenderEnum/RenderStatInfo";
import { Color } from "../../../maths/Color";
export declare class NativeWebGLEngine implements IRenderEngine {
    _context: WebGLRenderingContext | WebGL2RenderingContext;
    private _config;
    private _GLTextureContext;
    private _GLRenderDrawContext;
    private _GL2DRenderContext;
    _nativeObj: any;
    constructor(config: WebGlConfig, webglMode?: WebGLMode);
    createRenderStateComand(): RenderStateCommand;
    getUBOPointer(name: string): number;
    _addStatisticsInfo(info: RenderStatisticsInfo, value: number): void;
    get gl(): WebGLRenderingContext | WebGL2RenderingContext;
    get isWebGL2(): any;
    get webglConfig(): WebGlConfig;
    initRenderEngine(canvas: any): void;
    bindTexture(texture: BaseTexture): void;
    applyRenderStateCMD(cmd: RenderStateCommand): void;
    getCapable(capatableType: RenderCapable): boolean;
    viewport(x: number, y: number, width: number, height: number): void;
    scissor(x: number, y: number, width: number, height: number): void;
    scissorTest(value: boolean): void;
    clearRenderTexture(clearFlag: RenderClearFlag, clearcolor?: Color, clearDepth?: number): void;
    copySubFrameBuffertoTex(texture: BaseTexture, level: number, xoffset: number, yoffset: number, x: number, y: number, width: number, height: number): void;
    colorMask(r: boolean, g: boolean, b: boolean, a: boolean): void;
    getParams(params: RenderParams): number;
    createBuffer(targetType: BufferTargetType, bufferUsageType: BufferUsage): IRenderBuffer;
    createShaderInstance(vs: string, ps: string, attributeMap: {
        [name: string]: [number, ShaderDataType];
    }): IRenderShaderInstance;
    createVertexState(): IRenderVertexState;
    getTextureContext(): ITextureContext;
    getDrawContext(): IRenderDrawContext;
    get2DRenderContext(): IRender2DContext;
    getCreateRenderOBJContext(): IRenderOBJCreate;
    propertyNameToID(name: string): number;
    propertyIDToName(id: number): string;
    uploadUniforms(shader: IRenderShaderInstance, commandEncoder: CommandEncoder, shaderData: any, uploadUnTexture: boolean): number;
    uploadCustomUniforms(shader: IRenderShaderInstance, custom: any[], index: number, data: any): number;
    unbindVertexState(): void;
}
