import { Vector3 } from "../../../maths/Vector3";
export declare class NativeRenderState {
    _nativeObj: any;
    set cull(value: number);
    get cull(): number;
    set blend(value: number);
    get blend(): number;
    set srcBlend(value: number);
    get srcBlend(): number;
    set dstBlend(value: number);
    get dstBlend(): number;
    set srcBlendRGB(value: number);
    get srcBlendRGB(): number;
    set dstBlendRGB(value: number);
    get dstBlendRGB(): number;
    set srcBlendAlpha(value: number);
    get srcBlendAlpha(): number;
    set dstBlendAlpha(value: number);
    get dstBlendAlpha(): number;
    set blendEquation(value: number);
    get blendEquation(): number;
    set blendEquationRGB(value: number);
    get blendEquationRGB(): number;
    set blendEquationAlpha(value: number);
    get blendEquationAlpha(): number;
    set depthTest(value: number);
    get depthTest(): number;
    set depthWrite(value: boolean);
    get depthWrite(): boolean;
    set stencilWrite(value: boolean);
    get stencilWrite(): boolean;
    set stencilTest(value: number);
    get stencilTest(): number;
    set stencilRef(value: number);
    get stencilRef(): number;
    set stencilOp(value: Vector3);
    setNull(): void;
    constructor();
}
