import { IndexFormat } from "../../../RenderEngine/RenderEnum/IndexFormat";
import { VertexDeclaration } from "../../../RenderEngine/VertexDeclaration";
import { Resource } from "../../../resource/Resource";
import { Handler } from "../../../utils/Handler";
import { IClone } from "../../../utils/IClone";
import { Bounds } from "../../math/Bounds";
import { SubMesh } from "./SubMesh";
import { Color } from "../../../maths/Color";
import { Matrix4x4 } from "../../../maths/Matrix4x4";
import { Vector2 } from "../../../maths/Vector2";
import { Vector3 } from "../../../maths/Vector3";
import { Vector4 } from "../../../maths/Vector4";
import { MorphTargetData } from "./MorphTargetData";
export declare class Mesh extends Resource implements IClone {
    static MESH_INSTANCEBUFFER_TYPE_NORMAL: number;
    static MESH_INSTANCEBUFFER_TYPE_SIMPLEANIMATOR: number;
    static load(url: string, complete: Handler): void;
    morphTargetData: MorphTargetData;
    get inverseAbsoluteBindPoses(): Matrix4x4[];
    get vertexCount(): number;
    get indexCount(): number;
    get subMeshCount(): number;
    get bounds(): Bounds;
    set bounds(value: Bounds);
    get indexFormat(): IndexFormat;
    set indexFormat(value: IndexFormat);
    constructor(isReadable?: boolean);
    protected _disposeResource(): void;
    getSubMesh(index: number): SubMesh;
    getPositions(positions: Vector3[]): void;
    setPositions(positions: Vector3[]): void;
    getColors(colors: Color[]): void;
    setColors(colors: Color[]): void;
    getUVs(uvs: Vector2[], channel?: number): void;
    setUVs(uvs: Vector2[], channel?: number): void;
    getNormals(normals: Vector3[]): void;
    setNormals(normals: Vector3[]): void;
    getTangents(tangents: Vector4[]): void;
    setTangents(tangents: Vector4[]): void;
    getBoneWeights(boneWeights: Vector4[]): void;
    setBoneWeights(boneWeights: Vector4[]): void;
    getBoneIndices(boneIndices: Vector4[]): void;
    setBoneIndices(boneIndices: Vector4[]): void;
    markAsUnreadbale(): void;
    getVertexDeclaration(): VertexDeclaration;
    getVertices(): ArrayBuffer;
    setVertices(vertices: ArrayBuffer): void;
    getIndices(): Uint8Array | Uint16Array | Uint32Array;
    setIndices(indices: Uint8Array | Uint16Array | Uint32Array): void;
    calculateBounds(): void;
    cloneTo(destObject: any): void;
    clone(): any;
}
