import { JointBase } from "./JointBase";
import { RigidBody } from "../RigidBody";
export declare class WheelJoint extends JointBase {
    private static _temp;
    selfBody: RigidBody;
    otherBody: RigidBody;
    anchor: any[];
    collideConnected: boolean;
    axis: any[];
    private _frequency;
    private _dampingRatio;
    private _enableMotor;
    private _motorSpeed;
    private _maxMotorTorque;
    private _enableLimit;
    private _lowerTranslation;
    private _upperTranslation;
    protected _createJoint(): void;
    get frequency(): number;
    set frequency(value: number);
    get damping(): number;
    set damping(value: number);
    get enableMotor(): boolean;
    set enableMotor(value: boolean);
    get motorSpeed(): number;
    set motorSpeed(value: number);
    get maxMotorTorque(): number;
    set maxMotorTorque(value: number);
    get enableLimit(): boolean;
    set enableLimit(value: boolean);
    get lowerTranslation(): number;
    set lowerTranslation(value: number);
    get upperTranslation(): number;
    set upperTranslation(value: number);
}
