import { AlphaCmd } from "./cmd/AlphaCmd";
import { ClipRectCmd } from "./cmd/ClipRectCmd";
import { DrawCircleCmd } from "./cmd/DrawCircleCmd";
import { DrawCurvesCmd } from "./cmd/DrawCurvesCmd";
import { DrawImageCmd } from "./cmd/DrawImageCmd";
import { DrawLineCmd } from "./cmd/DrawLineCmd";
import { DrawLinesCmd } from "./cmd/DrawLinesCmd";
import { DrawPathCmd } from "./cmd/DrawPathCmd";
import { DrawPieCmd } from "./cmd/DrawPieCmd";
import { DrawPolyCmd } from "./cmd/DrawPolyCmd";
import { DrawRectCmd } from "./cmd/DrawRectCmd";
import { DrawTextureCmd } from "./cmd/DrawTextureCmd";
import { DrawTexturesCmd } from "./cmd/DrawTexturesCmd";
import { DrawTrianglesCmd } from "./cmd/DrawTrianglesCmd";
import { FillTextCmd } from "./cmd/FillTextCmd";
import { FillTextureCmd } from "./cmd/FillTextureCmd";
import { RestoreCmd } from "./cmd/RestoreCmd";
import { RotateCmd } from "./cmd/RotateCmd";
import { SaveCmd } from "./cmd/SaveCmd";
import { ScaleCmd } from "./cmd/ScaleCmd";
import { TransformCmd } from "./cmd/TransformCmd";
import { TranslateCmd } from "./cmd/TranslateCmd";
import { Matrix } from "../maths/Matrix";
import { Point } from "../maths/Point";
import { Rectangle } from "../maths/Rectangle";
import { Texture } from "../resource/Texture";
import { WordText } from "../utils/WordText";
export declare class Graphics {
    private _cmds;
    protected _vectorgraphArray: any[] | null;
    private _graphicBounds;
    constructor();
    destroy(): void;
    clear(recoverCmds?: boolean): void;
    _clearBoundsCache(onSizeChanged?: boolean): void;
    private _initGraphicBounds;
    get cmds(): any[];
    set cmds(value: any[]);
    addCmd(cmd: any): any;
    removeCmd(cmd: any): void;
    getBounds(realSize?: boolean): Rectangle;
    getBoundPoints(realSize?: boolean): any[];
    drawImage(texture: Texture, x?: number, y?: number, width?: number, height?: number, color?: string): DrawImageCmd | null;
    drawTexture(texture: Texture | null, x?: number, y?: number, width?: number, height?: number, matrix?: Matrix | null, alpha?: number, color?: string | null, blendMode?: string | null, uv?: number[]): DrawTextureCmd | null;
    drawTextures(texture: Texture, pos: any[], colors?: number[]): DrawTexturesCmd | null;
    drawTriangles(texture: Texture, x: number, y: number, vertices: Float32Array, uvs: Float32Array, indices: Uint16Array, matrix?: Matrix | null, alpha?: number, color?: string | number, blendMode?: string | null): DrawTrianglesCmd;
    fillTexture(texture: Texture, x: number, y: number, width?: number, height?: number, type?: string, offset?: Point | null, color?: string): FillTextureCmd | null;
    clipRect(x: number, y: number, width: number, height: number): ClipRectCmd;
    fillText(text: string | WordText, x: number, y: number, font: string, color: string, textAlign: string): FillTextCmd;
    fillBorderText(text: string | WordText, x: number, y: number, font: string, fillColor: string, textAlign: string, lineWidth: number, borderColor: string): FillTextCmd;
    strokeText(text: string | WordText, x: number, y: number, font: string, color: string, lineWidth: number, textAlign: string): FillTextCmd;
    alpha(alpha: number): AlphaCmd;
    transform(matrix: Matrix, pivotX?: number, pivotY?: number): TransformCmd;
    rotate(angle: number, pivotX?: number, pivotY?: number): RotateCmd;
    scale(scaleX: number, scaleY: number, pivotX?: number, pivotY?: number): ScaleCmd;
    translate(tx: number, ty: number): TranslateCmd;
    save(): SaveCmd;
    restore(): RestoreCmd;
    replaceTextColor(color: string): void;
    loadImage(url: string, x?: number, y?: number, width?: number, height?: number, complete?: Function | null): void;
    drawLine(fromX: number, fromY: number, toX: number, toY: number, lineColor: string, lineWidth?: number): DrawLineCmd;
    drawLines(x: number, y: number, points: any[], lineColor: any, lineWidth?: number): DrawLinesCmd | null;
    drawCurves(x: number, y: number, points: any[], lineColor: any, lineWidth?: number): DrawCurvesCmd;
    drawRect(x: number, y: number, width: number, height: number, fillColor: any, lineColor?: any, lineWidth?: number, percent?: boolean): DrawRectCmd;
    drawCircle(x: number, y: number, radius: number, fillColor: any, lineColor?: any, lineWidth?: number): DrawCircleCmd;
    drawPie(x: number, y: number, radius: number, startAngle: number, endAngle: number, fillColor: any, lineColor?: any, lineWidth?: number): DrawPieCmd;
    drawPoly(x: number, y: number, points: any[], fillColor: any, lineColor?: any, lineWidth?: number): DrawPolyCmd;
    drawPath(x: number, y: number, paths: any[], brush?: any, pen?: any): DrawPathCmd;
    draw9Grid(texture: Texture, x: number, y: number, width: number, height: number, sizeGrid: any[], color?: string): void;
}
