import { UIComponent } from "./UIComponent";
import { AutoBitmap } from "./AutoBitmap";
import { Texture } from "../resource/Texture";
import { Handler } from "../utils/Handler";
export declare class Clip extends UIComponent {
    protected _sources: Texture[];
    protected _skin: string;
    protected _clipX: number;
    protected _clipY: number;
    protected _clipWidth: number;
    protected _clipHeight: number;
    protected _autoPlay: boolean;
    protected _interval: number;
    protected _complete: Handler;
    protected _isPlaying: boolean;
    protected _index: number;
    protected _clipChanged: boolean;
    protected _group: string;
    protected _toIndex: number;
    _graphics: AutoBitmap;
    constructor(url?: string, clipX?: number, clipY?: number);
    protected createChildren(): void;
    protected _onDisplay(e?: boolean): void;
    get skin(): string;
    set skin(value: string);
    _setSkin(url: string): Promise<void>;
    protected _skinLoaded(): void;
    get clipX(): number;
    set clipX(value: number);
    get clipY(): number;
    set clipY(value: number);
    get clipWidth(): number;
    set clipWidth(value: number);
    get clipHeight(): number;
    set clipHeight(value: number);
    protected changeClip(): void;
    protected loadComplete(url: string, img: Texture): void;
    get sources(): Texture[];
    set sources(value: Texture[]);
    get group(): string;
    set group(value: string);
    _setWidth(value: number): void;
    _setHeight(value: number): void;
    protected measureWidth(): number;
    protected measureHeight(): number;
    get sizeGrid(): string;
    set sizeGrid(value: string);
    get index(): number;
    set index(value: number);
    get total(): number;
    get autoPlay(): boolean;
    set autoPlay(value: boolean);
    get interval(): number;
    set interval(value: number);
    get isPlaying(): boolean;
    set isPlaying(value: boolean);
    play(from?: number, to?: number): void;
    protected _loop(): void;
    stop(): void;
    set_dataSource(value: any): void;
    protected _setClipChanged(): void;
}
