import { Box } from "./Box";
import { VScrollBar } from "./VScrollBar";
import { HScrollBar } from "./HScrollBar";
import { ScrollBar } from "./ScrollBar";
import { Node } from "../display/Node";
import { Sprite } from "../display/Sprite";
import { ScrollType } from "./Styles";
export declare class Panel extends Box {
    protected _content: Box;
    protected _vScrollBar: VScrollBar;
    protected _hScrollBar: HScrollBar;
    protected _scrollChanged: boolean;
    protected _usedCache: string;
    protected _elasticEnabled: boolean;
    protected _scrollType: ScrollType;
    protected _vScrollBarSkin: string;
    protected _hScrollBarSkin: string;
    constructor();
    destroy(destroyChild?: boolean): void;
    destroyChildren(): void;
    protected createChildren(): void;
    addChild<T extends Node>(child: T): T;
    private onResize;
    addChildAt(child: Node, index: number): Node;
    removeChild(child: Node): Node;
    removeChildAt(index: number): Node;
    removeChildren(beginIndex?: number, endIndex?: number): Node;
    getChildAt(index: number): Node;
    getChildByName(name: string): Node;
    getChildIndex(child: Node): number;
    get numChildren(): number;
    private changeScroll;
    protected _sizeChanged(): void;
    get contentWidth(): number;
    get contentHeight(): number;
    private setContentSize;
    _setWidth(value: number): void;
    _setHeight(value: number): void;
    get scrollType(): ScrollType;
    set scrollType(value: ScrollType);
    private createHScrollBar;
    private createVScrollBar;
    get vScrollBarSkin(): string;
    set vScrollBarSkin(value: string);
    get hScrollBarSkin(): string;
    set hScrollBarSkin(value: string);
    get vScrollBar(): ScrollBar;
    get hScrollBar(): ScrollBar;
    get content(): Sprite;
    protected onScrollBarChange(scrollBar: ScrollBar): void;
    scrollTo(x?: number, y?: number): void;
    refresh(): void;
    set cacheAs(value: string);
    get cacheAs(): string;
    get elasticEnabled(): boolean;
    set elasticEnabled(value: boolean);
    private onScrollStart;
    private onScrollEnd;
    protected _setScrollChanged(): void;
}
