import { Matrix } from "laya/maths/Matrix";
export declare class ByteEx {
    static BIG_ENDIAN: string;
    static LITTLE_ENDIAN: string;
    private static _sysEndian;
    protected _xd_: boolean;
    private _allocated_;
    protected _d_: any;
    protected _u8d_: any;
    protected _pos_: number;
    protected _length: number;
    static getSystemEndian(): string;
    constructor(data?: any);
    get buffer(): ArrayBuffer;
    get endian(): string;
    set endian(value: string);
    set length(value: number);
    get length(): number;
    private _resizeBuffer;
    getString(): string;
    readString(): string;
    getFloat32Array(start: number, len: number): any;
    readFloat32Array(start: number, len: number): any;
    getUint8Array(start: number, len: number): Uint8Array;
    readUint8Array(start: number, len: number): Uint8Array;
    getInt16Array(start: number, len: number): any;
    readInt16Array(start: number, len: number): any;
    getFloat32(): number;
    readFloat32(): number;
    getFloat64(): number;
    readFloat64(): number;
    writeFloat32(value: number): void;
    writeFloat64(value: number): void;
    getInt32(): number;
    readInt32(): number;
    getUint32(): number;
    readUint32(): number;
    writeInt32(value: number): void;
    writeUint32(value: number): void;
    getInt16(): number;
    readInt16(): number;
    getUint16(): number;
    readUint16(): number;
    writeUint16(value: number): void;
    writeInt16(value: number): void;
    getUint8(): number;
    readUint8(): number;
    writeUint8(value: number): void;
    _getUInt8(pos: number): number;
    _readUInt8(pos: number): number;
    _getUint16(pos: number): number;
    _readUint16(pos: number): number;
    _getMatrix(): Matrix;
    _readMatrix(): Matrix;
    private _rUTF;
    getCustomString(len: number): string;
    readCustomString(len: number): string;
    get pos(): number;
    set pos(value: number);
    get bytesAvailable(): number;
    clear(): void;
    __getBuffer(): ArrayBuffer;
    writeUTFBytes(value: string): void;
    writeUTFString(value: string): void;
    readUTFString(): string;
    getUTFString(): string;
    readUTFBytes(len?: number): string;
    getUTFBytes(len?: number): string;
    writeByte(value: number): void;
    readByte(): number;
    getByte(): number;
    _ensureWrite(lengthToEnsure: number): void;
    writeArrayBuffer(arraybuffer: any, offset?: number, length?: number): void;
}
