export declare class Browser {
    static userAgent: string;
    static onMobile: boolean;
    static onIOS: boolean;
    static onMac: boolean;
    static onIPhone: boolean;
    static onIPad: boolean;
    static onAndroid: boolean;
    static onWP: boolean;
    static onQQBrowser: boolean;
    static onMQQBrowser: boolean;
    static onSafari: boolean;
    static onChrome: boolean;
    static onIE: boolean;
    static onWeiXin: boolean;
    static onPC: boolean;
    static onMiniGame: boolean;
    static onBDMiniGame: boolean;
    static onKGMiniGame: boolean;
    static onQGMiniGame: boolean;
    static onVVMiniGame: boolean;
    static onAlipayMiniGame: boolean;
    static onQQMiniGame: boolean;
    static onBLMiniGame: boolean;
    static onTTMiniGame: boolean;
    static onHWMiniGame: boolean;
    static onTBMiniGame: boolean;
    static onFirefox: boolean;
    static onEdge: boolean;
    static onLayaRuntime: boolean;
    static platform: number;
    static PLATFORM_PC: number;
    static PLATFORM_ANDROID: number;
    static PLATFORM_IOS: number;
    static supportWebAudio: boolean;
    static supportLocalStorage: boolean;
    static canvas: any;
    static context: CanvasRenderingContext2D;
    private static _window;
    private static _document;
    private static _container;
    private static _pixelRatio;
    private static _clientWidth;
    private static _clientHeight;
    static mainCanvas: any;
    private static hanzi;
    private static fontMap;
    static measureText: Function;
    static get _isMiniGame(): boolean;
    static createElement(type: string): any;
    static getElementById(type: string): any;
    static removeElement(ele: any): void;
    static now(): number;
    static get clientWidth(): number;
    static set clientWidth(value: number);
    static get clientHeight(): number;
    static set clientHeight(value: number);
    static get width(): number;
    static get height(): number;
    static get pixelRatio(): number;
    static get container(): any;
    static set container(value: any);
    static get window(): any;
    static get document(): any;
    static getQueryString(name: string): string;
}
