import { Point } from "../maths/Point";
export interface ITouchInfo {
    touchId: number;
    readonly pos: Point;
}
export declare class Event {
    static readonly EMPTY: Readonly<Event>;
    static MOUSE_DOWN: string;
    static MOUSE_UP: string;
    static RIGHT_MOUSE_DOWN: string;
    static RIGHT_MOUSE_UP: string;
    static CLICK: string;
    static RIGHT_CLICK: string;
    static MOUSE_MOVE: string;
    static MOUSE_OVER: string;
    static MOUSE_OUT: string;
    static MOUSE_WHEEL: string;
    static ROLL_OVER: string;
    static ROLL_OUT: string;
    static DOUBLE_CLICK: string;
    static MOUSE_DRAG: string;
    static MOUSE_DRAG_END: string;
    static DRAG_START: string;
    static DRAG_MOVE: string;
    static DRAG_END: string;
    static KEY_DOWN: string;
    static KEY_PRESS: string;
    static KEY_UP: string;
    static CHANGE: string;
    static CHANGED: string;
    static WILL_RESIZE: string;
    static RESIZE: string;
    static ADDED: string;
    static REMOVED: string;
    static DISPLAY: string;
    static UNDISPLAY: string;
    static ERROR: string;
    static COMPLETE: string;
    static LOADED: string;
    static READY: string;
    static PROGRESS: string;
    static INPUT: string;
    static RENDER: string;
    static OPEN: string;
    static MESSAGE: string;
    static CLOSE: string;
    static FRAME: string;
    static ENTER: string;
    static SELECT: string;
    static BLUR: string;
    static FOCUS: string;
    static VISIBILITY_CHANGE: string;
    static FOCUS_CHANGE: string;
    static PLAYED: string;
    static PAUSED: string;
    static STOPPED: string;
    static START: string;
    static END: string;
    static LINK: string;
    static LABEL: string;
    static FULL_SCREEN_CHANGE: string;
    static DEVICE_LOST: string;
    static TRANSFORM_CHANGED: string;
    static LAYERCHANGE: string;
    static staticMask: string;
    static TRIGGER_ENTER: string;
    static TRIGGER_STAY: string;
    static TRIGGER_EXIT: string;
    static COLLISION_ENTER: string;
    static COLLISION_STAY: string;
    static COLLISION_EXIT: string;
    static JOINT_BREAK: string;
    static isMouseEvent(type: string): boolean;
    type: string;
    target: any;
    currentTarget: any;
    touchId: number;
    readonly touchPos: Point;
    isDblClick: boolean;
    delta: number;
    button: number;
    nativeEvent: MouseEvent | TouchEvent | WheelEvent | KeyboardEvent;
    constructor();
    setTo(type: string, currentTarget: any, target: any): Event;
    stopPropagation(): void;
    get touches(): ReadonlyArray<Readonly<ITouchInfo>>;
    get altKey(): boolean;
    get ctrlKey(): boolean;
    get shiftKey(): boolean;
    get metaKey(): boolean;
    get key(): string;
    get keyCode(): number;
    get charCode(): string;
    get keyLocation(): number;
    get stageX(): number;
    get stageY(): number;
}
