export declare enum RenderCapable {
    Element_Index_Uint32 = 0,
    TextureFormat_R32G32B32A32 = 1,
    TextureFormat_R16G16B16A16 = 2,
    Texture_anisotropic = 3,
    RenderTextureFormat_R16G16B16A16 = 4,
    RenderTextureFormat_Depth = 5,
    RenderTextureFormat_ShadowMap = 6,
    Vertex_VAO = 7,
    DrawElement_Instance = 8,
    Shader_TextureLod = 9,
    COMPRESS_TEXTURE_S3TC = 10,
    COMPRESS_TEXTURE_S3TC_SRGB = 11,
    COMPRESS_TEXTURE_PVRTC = 12,
    COMPRESS_TEXTURE_ETC1 = 13,
    COMPRESS_TEXTURE_ETC = 14,
    COMPRESS_TEXTURE_ASTC = 15,
    Texture_SRGB = 16,
    MSAA = 17,
    UnifromBufferObject = 18,
    Texture3D = 19,
    Texture_FloatLinearFiltering = 20,
    Texture_HalfFloatLinearFiltering = 21
}
