import { BaseTexture } from "./BaseTexture";
import { RenderTargetFormat } from "../RenderEngine/RenderEnum/RenderTargetFormat";
import { InternalRenderTarget } from "../RenderEngine/RenderInterface/InternalRenderTarget";
import { IRenderTarget } from "../RenderEngine/RenderInterface/IRenderTarget";
import { Color } from "../maths/Color";
export declare class RenderTexture2D extends BaseTexture implements IRenderTarget {
    private static _currentActive;
    static _clearColor: Color;
    static _clearLinearColor: Color;
    private _lastRT;
    private _lastWidth;
    private _lastHeight;
    private static rtStack;
    static defuv: any[];
    static flipyuv: any[];
    static get currentActive(): RenderTexture2D;
    private _depthStencilFormat;
    private _colorFormat;
    get depthStencilFormat(): number;
    get defaultTexture(): BaseTexture;
    getIsReady(): boolean;
    get sourceWidth(): number;
    get sourceHeight(): number;
    get offsetX(): number;
    get offsetY(): number;
    depthStencilTexture: BaseTexture;
    _renderTarget: InternalRenderTarget;
    _isCameraTarget: boolean;
    constructor(width: number, height: number, format?: RenderTargetFormat, depthStencilFormat?: RenderTargetFormat);
    get isCube(): boolean;
    get samples(): number;
    get generateMipmap(): boolean;
    static pushRT(): void;
    static popRT(): void;
    start(): void;
    end(): void;
    restore(): void;
    clear(r?: number, g?: number, b?: number, a?: number): void;
    getData(x: number, y: number, width: number, height: number): ArrayBufferView;
}
