import { Vector3 } from "../../maths/Vector3";
export declare class RenderState {
    static CULL_NONE: number;
    static CULL_FRONT: number;
    static CULL_BACK: number;
    static BLEND_DISABLE: number;
    static BLEND_ENABLE_ALL: number;
    static BLEND_ENABLE_SEPERATE: number;
    static BLENDPARAM_ZERO: number;
    static BLENDPARAM_ONE: number;
    static BLENDPARAM_SRC_COLOR: number;
    static BLENDPARAM_ONE_MINUS_SRC_COLOR: number;
    static BLENDPARAM_DST_COLOR: number;
    static BLENDPARAM_ONE_MINUS_DST_COLOR: number;
    static BLENDPARAM_SRC_ALPHA: number;
    static BLENDPARAM_ONE_MINUS_SRC_ALPHA: number;
    static BLENDPARAM_DST_ALPHA: number;
    static BLENDPARAM_ONE_MINUS_DST_ALPHA: number;
    static BLENDPARAM_SRC_ALPHA_SATURATE: number;
    static BLENDPARAM_BLENDCOLOR: number;
    static BLENDPARAM_BLEND_ONEMINUS_COLOR: number;
    static BLENDEQUATION_ADD: number;
    static BLENDEQUATION_SUBTRACT: number;
    static BLENDEQUATION_REVERSE_SUBTRACT: number;
    static BLENDEQUATION_MIN: number;
    static BLENDEQUATION_MAX: number;
    static DEPTHTEST_OFF: number;
    static DEPTHTEST_NEVER: number;
    static DEPTHTEST_LESS: number;
    static DEPTHTEST_EQUAL: number;
    static DEPTHTEST_LEQUAL: number;
    static DEPTHTEST_GREATER: number;
    static DEPTHTEST_NOTEQUAL: number;
    static DEPTHTEST_GEQUAL: number;
    static DEPTHTEST_ALWAYS: number;
    static STENCILTEST_OFF: number;
    static STENCILTEST_NEVER: number;
    static STENCILTEST_LESS: number;
    static STENCILTEST_EQUAL: number;
    static STENCILTEST_LEQUAL: number;
    static STENCILTEST_GREATER: number;
    static STENCILTEST_NOTEQUAL: number;
    static STENCILTEST_GEQUAL: number;
    static STENCILTEST_ALWAYS: number;
    static STENCILOP_KEEP: number;
    static STENCILOP_ZERO: number;
    static STENCILOP_REPLACE: number;
    static STENCILOP_INCR: number;
    static STENCILOP_INCR_WRAP: number;
    static STENCILOP_DECR: number;
    static STENCILOP_DECR_WRAP: number;
    static STENCILOP_INVERT: number;
    cull: number;
    blend: number;
    srcBlend: number;
    dstBlend: number;
    srcBlendRGB: number;
    dstBlendRGB: number;
    srcBlendAlpha: number;
    dstBlendAlpha: number;
    blendEquation: number;
    blendEquationRGB: number;
    blendEquationAlpha: number;
    depthTest: number;
    depthWrite: boolean;
    stencilWrite: boolean;
    stencilTest: number;
    stencilRef: number;
    stencilOp: Vector3;
    constructor();
}
