import { Sprite } from "../display/Sprite";
import { VideoTexture } from "./VideoTexture";
export declare class VideoNode extends Sprite {
    private _videoTexture;
    private _internalTex;
    constructor();
    get videoTexture(): VideoTexture;
    set videoTexture(value: VideoTexture);
    get source(): string;
    set source(value: string);
    load(url: string): void;
    play(): void;
    pause(): void;
    reload(): void;
    canPlayType(type: string): CanPlayTypeResult;
    private onVideoMetaLoaded;
    get buffered(): any;
    get currentSrc(): string;
    get currentTime(): number;
    set currentTime(value: number);
    set volume(value: number);
    get volume(): number;
    get readyState(): any;
    get videoWidth(): number;
    get videoHeight(): number;
    get duration(): number;
    get ended(): boolean;
    get error(): MediaError;
    get loop(): boolean;
    set loop(value: boolean);
    get playbackRate(): number;
    set playbackRate(value: number);
    get muted(): boolean;
    set muted(value: boolean);
    get paused(): boolean;
    get preload(): string;
    set preload(value: string);
    get seekable(): any;
    get seeking(): boolean;
    _setX(value: number): void;
    _setY(value: number): void;
    set_width(value: number): void;
    set_height(value: number): void;
    destroy(detroyChildren?: boolean): void;
}
