import { Sprite } from "laya/display/Sprite";
import { Handler } from "laya/utils/Handler";
export declare class DebugPanel {
    constructor();
    static I: DebugPanel;
    private static overlay;
    private static _enable;
    static enable(underGame?: boolean, bgColor?: string): void;
    static ChildrenSign: string;
    static LabelSign: string;
    static getSpriteTreeArr(sprite: Sprite): any;
    static displayTypes: any;
    static displayKeys: any[];
    static tObjKeys: any[];
    tShowObj: any;
    preValueO: any;
    static noDisplayKeys: any;
    static Bottom: string;
    static Right: string;
    static sideType: string;
    private removeNoDisplayKeys;
    updateShowKeys(): void;
    static getObjectData(data: any): any[];
    div: any;
    debug_view: any;
    height: number;
    width: number;
    clickedHandler: Handler;
    private _init;
    private initNewDivs;
    private dragArea;
    private static getOffset;
    private initTreeWidthDrag;
    private initDragWork;
    private onClickSelected;
    private updateLoop;
    private onSelectItem;
    static mParseFloat(v: any): number;
    private onValueChange;
    showTargetInfo(tTarget: any): void;
    private fromMe;
    private adptPos;
    private _treeDataList;
    setRoot(sprite: Sprite): void;
    getDataByID(targetID: string, nodeO: any): any;
    getDataByTarget(target: any, nodeO: any): any;
}
